# Stub interface for the postbound package

# Set in __init__.py from the installed distribution metadata. Declared here because this
# stub shadows __init__.py for type checkers.
__version__: str

from . import (
    bench,
    db,
    duckdb,
    mysql,
    opt,
    parser,
    postgres,
    qal,
    relalg,
    train,
    transform,
    util,
    validation,
    vis,
    workloads,
)
from ._core import (
    BoundColumnReference,
    Cardinality,
    ColumnReference,
    Cost,
    IntermediateOperator,
    JoinOperator,
    PhysicalOperator,
    ScanOperator,
    TableReference,
    TimeMs,
    UnboundColumnError,
    VirtualTableError,
)
from ._hints import (
    DirectionalJoinOperatorAssignment,
    ExecutionMode,
    HintType,
    JoinOperatorAssignment,
    JoinTree,
    LogicalJoinTree,
    PhysicalOperatorAssignment,
    PlanParameterization,
    ScanOperatorAssignment,
    jointree_from_plan,
    operators_from_plan,
    parameters_from_plan,
)
from ._pipelines import (
    IncrementalOptimizationPipeline,
    IntegratedOptimizationPipeline,
    MultiStageOptimizationPipeline,
    OptimizationPipeline,
    OptimizationSettings,
    TextBookOptimizationPipeline,
)
from ._qep import (
    PlanEstimates,
    PlanMeasures,
    PlanParams,
    QueryPlan,
    SortKey,
    Subplan,
)
from ._stages import (
    CardinalityEstimator,
    CompleteOptimizationAlgorithm,
    CostModel,
    IncrementalOptimizationStep,
    JoinOrderOptimization,
    OptimizationStage,
    ParameterGeneration,
    PhysicalOperatorSelection,
    PlanEnumerator,
    as_complete_algorithm,
)
from .db import Database
from .parser import parse_query
from .qal import SqlQuery
from .workloads import Workload

__all__ = [
    "BoundColumnReference",
    "Cardinality",
    "CardinalityEstimator",
    "ColumnReference",
    "CompleteOptimizationAlgorithm",
    "Cost",
    "CostModel",
    "Database",
    "DirectionalJoinOperatorAssignment",
    "ExecutionMode",
    "HintType",
    "IncrementalOptimizationPipeline",
    "IncrementalOptimizationStep",
    "IntegratedOptimizationPipeline",
    "IntermediateOperator",
    "JoinOperator",
    "JoinOperatorAssignment",
    "JoinOrderOptimization",
    "JoinTree",
    "LogicalJoinTree",
    "MultiStageOptimizationPipeline",
    "OptimizationPipeline",
    "OptimizationSettings",
    "OptimizationStage",
    "ParameterGeneration",
    "PhysicalOperator",
    "PhysicalOperatorAssignment",
    "PhysicalOperatorSelection",
    "PlanEnumerator",
    "PlanEstimates",
    "PlanMeasures",
    "PlanParameterization",
    "PlanParams",
    "QueryPlan",
    "ScanOperator",
    "ScanOperatorAssignment",
    "SortKey",
    "SqlQuery",
    "Subplan",
    "TableReference",
    "TextBookOptimizationPipeline",
    "TimeMs",
    "UnboundColumnError",
    "VirtualTableError",
    "Workload",
    "as_complete_algorithm",
    "bench",
    "db",
    "duckdb",
    "jointree_from_plan",
    "mysql",
    "operators_from_plan",
    "opt",
    "parameters_from_plan",
    "parse_query",
    "parser",
    "postgres",
    "qal",
    "relalg",
    "train",
    "transform",
    "util",
    "validation",
    "vis",
    "workloads",
]
